version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers

    working_directory: ~/repo

    steps:
      # We have `node-hid` as a dependency, which won't build on certain Linux systems without installing libusb first
      - type: shell
        name: Install System Dependencies
        command: sudo apt-get update && sudo apt install -y libusb-1.0-0 libusb-1.0-0-dev

      - checkout
        - run: wget https://dist.ipfs.io/go-ipfs/v0.4.11/go-ipfs_v0.4.11_linux-amd64.tar.gz
        - run: tar xvfz go-ipfs_v0.4.11_linux-amd64.tar.gz
        - run: sudo cp go-ipfs/ipfs /usr/local/bin
        - run: ipfs init
        - run: echo $IPFS_KEY > ~/.ipfs/keystore/eab2d8ae-9e23-4912-9d7b-72fd6b03a28
        

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: npm run build
      - run: ipfs daemon
      - run: dcl deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/